### PR TITLE
Return conflict error for incorrect id in PATCH

### LINKED ISSUE #288: PATCHing with id hands over the ID given in JSON, not the one given in URL
# Steps to reproduce

1. Create an API for CRUD operations without any relations
2. Create an instance:
```sh
$ curl -d '{"data":{"type":"hosts","attributes":{"Name":"test.example.com"}}}' http://localhost:8080/v1/hosts |jq
######################################################################## 100,0%
{
  "data": {
    "type": "hosts",
    "id": "1",
    "attributes": {
      "Name": "test.example.com",
      "IP": {
        "IP": "",
        "Zone": ""
      },
      "Vars": null
    }
  },
  "meta": {
    "author": "Markus W Mahlberg",
    "license": "GPL-3.0",
    "license-url": "https://www.gnu.org/licenses/gpl-3.0-standalone.html"
  }
}
```
3. Create a second instance:

```sh
curl -d '{"data":{"type":"hosts","attributes":{"Name":"test2.example.com"}}}' http://localhost:8080/v1/hosts |jq
######################################################################## 100,0%
{
  "data": {
    "type": "hosts",
    "id": "2",
    "attributes": {
      "Name": "test2.example.com",
      "IP": {
        "IP": "",
        "Zone": ""
      },
      "Vars": null
    }
  },
  "meta": {
    "author": "Markus W Mahlberg",
    "license": "GPL-3.0",
    "license-url": "https://www.gnu.org/licenses/gpl-3.0-standalone.html"
  }
}
```

3. Check the instances are created properly
```sh
$ curl  http://localhost:8080/v1/hosts | jq
######################################################################## 100,0%
{
  "data": [
    {
      "type": "hosts",
      "id": "1",
      "attributes": {
        "Name": "test.example.com",
        "IP": {
          "IP": "",
          "Zone": ""
        },
        "Vars": null
      }
    },
    {
      "type": "hosts",
      "id": "2",
      "attributes": {
        "Name": "test2.example.com",
        "IP": {
          "IP": "",
          "Zone": ""
        },
        "Vars": null
      }
    }
  ],
  "meta": {
    "author": "Markus W Mahlberg",
    "license": "GPL-3.0",
    "license-url": "https://www.gnu.org/licenses/gpl-3.0-standalone.html"
  }
}
```
4. Patch instance with ID 1 albeit calling the URL of ID 2:
```sh
curl -X PATCH -d '{"data":{"type":"hosts","id":"1","attributes":{"Vars":{"foo":"bar"}}}}' http://localhost:8080/v1/hosts/2
```

5. View result:

```sh
$ curl  http://localhost:8080/v1/hosts | jq
######################################################################## 100,0%
{
  "data": [
    {
      "type": "hosts",
      "id": "1",
      "attributes": {
        "Name": "test2.example.com",
        "IP": {
          "IP": "",
          "Zone": ""
        },
        "Vars": {
          "foo": "bar"
        }
      }
    },
    {
      "type": "hosts",
      "id": "2",
      "attributes": {
        "Name": "test2.example.com",
        "IP": {
          "IP": "",
          "Zone": ""
        },
        "Vars": null
      }
    }
  ],
  "meta": {
    "author": "Markus W Mahlberg",
    "license": "GPL-3.0",
    "license-url": "https://www.gnu.org/licenses/gpl-3.0-standalone.html"
  }
}
```

The update of the ID works two, effectively creating a new record when using a sloppy resource or storage implementation.

Since both the ID given in JSON and the ID given in the URL are known very early, this actually should fail equally early with `http.StatusBadRequest` or, with a bit of a stretch, with `http.StatusConflict`, based on http://jsonapi.org/format/#crud-updating-responses-409

This behaviour would prevent even sloppy implementation of Resource or a storage from experiencing potentially catastrophic overwrites and eliminate the need to check for the cases illustrated in the Resource implementation.

### PR DESCRIPTION
**Pull request by wwwdata**
This fixes #288

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -699,6 +699,12 @@ func (res *resource) handleUpdate(c APIContexter, w http.ResponseWriter, r *http
 		return NewHTTPError(nil, err.Error(), http.StatusNotAcceptable)
 	}
 
+	identifyable, ok := updatingObj.Interface().(jsonapi.MarshalIdentifier)
```
Comment (sharpner) [inline api.go]: typo: identifiable :)
